add version
aliyun/aliyun-log-flume pull request #7
Opened 2019-09-29 08:53 UTC by jkaka

2019-10-27 08:04 UTC, liketic requested changes

2019-10-27 08:04 UTC, liketic commented on src/main/java/com/aliyun/loghub/flume/sink/LoghubSink.java
> +import static com.aliyun.loghub.flume.Constants.*;
为什么这里要用*

2019-10-27 08:04 UTC, liketic commented on src/main/java/com/aliyun/loghub/flume/sink/LoghubSink.java
> +        if(StringUtils.isEmpty(userAgent)){
提交之前先格式化一下

2019-10-27 08:04 UTC, liketic commented on src/main/java/com/aliyun/loghub/flume/utils/VersionInfoUtils.java
> +            defaultUserAgent = USER_AGENT_PREFIX + "-" + getVersion()+"/" + System.getProperty("java.version");
提交之前先格式化

2019-10-27 08:04 UTC, liketic commented on src/main/java/com/aliyun/loghub/flume/Constants.java
> +    public static final String LOG_USER_AGENT = "USER_AGENT";
为什么这个配置和其他的配置命名方式不一样？

2019-10-27 08:05 UTC, liketic commented
@jkaka 麻烦把标题改成 "Create user agent from version"

2019-10-28 07:22 UTC, jkaka commented on src/main/java/com/aliyun/loghub/flume/sink/LoghubSink.java
> +import static com.aliyun.loghub.flume.Constants.*;
已修改

2019-10-28 07:23 UTC, jkaka commented on src/main/java/com/aliyun/loghub/flume/sink/LoghubSink.java
> +        if(StringUtils.isEmpty(userAgent)){
已格式化

2019-10-28 07:24 UTC, jkaka commented on src/main/java/com/aliyun/loghub/flume/utils/VersionInfoUtils.java
> +            defaultUserAgent = USER_AGENT_PREFIX + "-" + getVersion()+"/" + System.getProperty("java.version");
已格式化

2019-10-28 07:24 UTC, jkaka commented on src/main/java/com/aliyun/loghub/flume/Constants.java
> +    public static final String LOG_USER_AGENT = "USER_AGENT";
已修改为userAgent

2019-10-29 07:26 UTC, merged